### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by Boco10** [machour/yii2-notifications#1]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package machour/yii2-notifications could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by machour** [comment]
This is because your "minimum-stability" is set to "stable" in your composer.json file.
Set it to dev to get this package

**Comment by Boco10** [comment]
You should mention this in the instructions or don't request "*" rather "@dev". Meanwhile i am not really familiar with this, just an idea which i see in other repositories. Thanks

**Comment by machour** [comment]
You're right, fixed the instructions. Thanks!
