### ISSUE TITLE
Any plan to make third party Independent js in version control via using bower asset?

### ISSUE THREAD

**Issue by su-xiaolin** [machour/yii2-notifications#11]

**Comment by machour** [comment]
This is what I was doing when I first developed the module. I was including the JS libraries in composer via bower, but I saw two issues:
  - It is a **lot** of files to download if you plan to use just a particular theme
  - Some libraries wasn't bower enabled, and I didn't plan on maintaining bower packages for them

Is that related to your previous bug entry?
