### ISSUE TITLE
Have notification on pop up once

### ISSUE THREAD

**Issue by michaelst** [machour/yii2-notifications#13]
If a notification hasn't been marked as seen it will get a pop up and be displayed in the drop down. After the initial pop up I don't think it should pop up on every page load until it has been seen.

**Comment by jsobers1331** [comment]
I agree

**Comment by michaelst** [comment]
I created a fork that does this https://github.com/michaelst/yii2-notifications

**Comment by machour** [comment]
I'll review your PR tomorrow, promise.

**Comment by jsobers1331** [comment]
I'm currently having trouble getting it to display in my yii advanced installation. But I can't figure out why the UI is not updating even when I'm using the triggers in the controllers. Was hoping documentation on the external site would clarify it for me.

**Comment by machour** [comment]
@jsobers1331 please open another issue for this. (and do provide some additonal information: is the xhr fired ? what's the response ? etc.)

**Comment by machour** [comment]
@michaelst thank you for the PR, good idea!
I added some comments on your changes, could you review them ?
Once the PR updated, I'll pull it locally, test it, and if it's ok I'll merge it
