### ISSUE TITLE
The online site is 404

### ISSUE THREAD

**Issue by lichunqiang** [machour/yii2-notifications#15]

**Comment by machour** [comment]
Fixed, thanks !

**Comment by jsobers1331** [comment]
http://machour.idk.tn/yii2-kitchen-sink/site/yii2-notifications is 404 again

**Comment by machour** [comment]
Please use the https version instead : https://machour.idk.tn/yii2-kitchen-sink/site/yii2-notifications

**Comment by michaelst** [comment]
you should setup your apache to redirect http to https

**Comment by machour** [comment]
done @michaelst, there was some faulty vhost file taking precedence

**Comment by jsobers1331** [comment]
https://github.com/machour/yii2-notifications/pull/17/commits/c0005a0fe0c45af20edee6b37bcf6ef4d4b1253f
