### ISSUE TITLE
NotificationAsset and Font Awesome

### ISSUE THREAD

**Issue by michaelst** [machour/yii2-notifications#16]
NotificationAsset is pointing to a different location for font awesome. I get this error with your code "Class rmrevin\yii\fontawesome\cdn\AssetBundle does not exist". It seems mine installed in this location
'rmrevin\yii\fontawesome\AssetBundle', is there something I need to do so I don't have to keep fixing this when I run composer update.

**Comment by machour** [comment]
@michaelst it seems that my composer.json was missing the requirement of "rmrevin/yii2-fontawesome": "~2.15"
both calls with \cdn or without it seems to work, so I removed it anyway

**Comment by michaelst** [comment]
After re initializing yii both also work for me

**Comment by machour** [comment]
thanks for your feedback !
currently reviewing your PR
