### ISSUE TITLE
Growl Notification isn't showing on frontend

### ISSUE THREAD

**Issue by jsobers1331** [machour/yii2-notifications#18]
I copied the code into my main layout which was provided in https://machour.idk.tn/yii/machour/yii2-notifications/Usage.md and the PHP snippet is not working for me.

From what I can tell, XHR is being fired based on my logs:

Route	'notifications/notifications/poll'
Action	'machour\\yii2\\notifications\\controllers\\NotificationsController::actionPoll()'
Parameters	[
    0 => '0'
]

Edit:
The database table is being updated with the key information as provided in the component with each trigger, so i know the trigger is working.

Or is this something that only works with AdminLTE ? ( as shown in your demo)

**Comment by machour** [comment]
Can you check in your browser console what's the request being fired and
what's the server response ?
Do you see JavaScript errors ?

**Comment by jsobers1331** [comment]
GET ...frontend/web/index.php/notifications/notifications/poll?seen=0 500 (Internal Server Error)send 
@ jquery.js:9175jQuery.extend.ajax 
@ jquery.js:8656options.poll
@ notifications.js:259(anonymous function) 
@ notifications.js:301
jquery.js:9175 

XHR finished loading: GET "...frontend/web/index.php/notifications/notifications/poll?seen=0".send 
@ jquery.js:9175jQuery.extend.ajax 
@ jquery.js:8656options.poll 
@ notifications.js:259(anonymous function) 
@ notifications.js:301
jquery.js:9175

**Comment by machour** [comment]
500 (Internal Server Error)
Did you run the migrations ? Try to find the error happening server side in yii logs.

**Comment by jsobers1331** [comment]
I run the migration when installing. Only one to create the table, I'll check to find the error in yii logs now.

**Comment by jsobers1331** [comment]
ok i got it to work.

In reviewing the logs i found out what was done wrong.

My mistake i did was i misunderstood your instructions on https://machour.idk.tn/yii/machour/yii2-notifications/Configuration.md and had pointed my notificationClass to my own Notifications in Models folder rather than pointing it to the components folder.

so instead of the path "app\models\Notification", The correct path was actually "app\components\Notification".

Which in my case was "frontend\components\Notification". Once i changed that in my config. The Growl messages appeared on page load at the bottom right hand corner.

**Comment by machour** [comment]
Glad you were able to fix that.
Do you feel that the documentation induced you in error ?

**Comment by jsobers1331** [comment]
@machour Yes, I do. 
Personally feel the documentation should have notificationClass path as "app\components\Notification".

**Comment by ajkosh** [comment]
@machour i am facing same issue.growls notifications are not displaying.
I checked in firbug there is no error.
Even there is html element div is not creating 
   ```<div id="growls" class="br"></div>```

**Comment by riki1994** [comment]
@machour my notifications growls are not displaying but the record in the datebase exist and the NotificationWidget show the notifications and they options but never the growls messages. How fix it?
