### ISSUE TITLE
Error when i follow the url created by the widget

### ISSUE THREAD

**Issue by Boco10** [machour/yii2-notifications#2]
src="/final_yii/frontend/web/assets/ceb237c3/notifications.js"
 src="/final_yii/frontend/web/assets/9b91480a/js/noty/packaged/jquery.noty.packaged.min.js"
jQuery(document).ready(function () {
Notifications({url:"/final_yii/frontend/web/index.php/notifications/notifications/poll",theme:"noty",timeout:"2000",delay:"5000"});
});

The url is not working.

ReflectionException
Class machour\yii2\notifications\Notifications does not exist

    1. in /var/www/html/final_yii/vendor/yiisoft/yii2/di/Container.php at line 415
    406407408409410411412413414415416417418419420421422423424

         * @return array the dependencies of the specified class.
         */
        protected function getDependencies($class)
        {
            if (isset($this->_reflections[$class])) {
                return [$this->_reflections[$class], $this->_dependencies[$class]];
            }
     
            $dependencies = [];
            $reflection = new ReflectionClass($class);
     
            $constructor = $reflection->getConstructor();
            if ($constructor !== null) {
                foreach ($constructor->getParameters() as $param) {
                    if ($param->isDefaultValueAvailable()) {
                        $dependencies[] = $param->getDefaultValue();
                    } else {
                        $c = $param->getClass();
                        $dependencies[] = Instance::of($c === null ? null : $c->getName());

**Comment by machour** [comment]
What is the URL ?

**Comment by Boco10** [comment]
url:"/final_yii/frontend/web/index.php/notifications/notifications/poll

**Comment by machour** [comment]
There was a typo in the configuration sample in README.md, the `class` key should instead point to 'machour\yii2\notifications\NotificationsModule'.
