### ISSUE TITLE
Error : Cannot instantiate abstract class

### ISSUE THREAD

**Issue by hirenbhut93** [machour/yii2-notifications#21]
I have give  `Cannot instantiate abstract class` when run `poll` action.

Why?

Please give this error solution?

**Comment by machour** [comment]
You need to implement your own Notification class. Please check the
documentation at
https://machour.idk.tn/yii/machour/yii2-notifications/Configuration.md

On Mon, Jun 13, 2016 at 2:37 PM, Hiren Bhut <notifications@github.com>
wrote:

> I have give Cannot instantiate abstract class when run poll action.
>
> Why?
>
> Please give this error solution?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/machour/yii2-notifications/issues/21>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AASlQt1s_9anLmkBYVgj6DGN3ALce2ryks5qLV0GgaJpZM4I0VYl>
> .
>



-- 
Mehdi Achour
