### ISSUE TITLE
Too many messages , how to limit ?

### ISSUE THREAD

**Issue by pigochu** [machour/yii2-notifications#25]
Hi

How to configure max display messages in dropdown item ? 

![image](https://cloud.githubusercontent.com/assets/1013744/21093004/75113cd2-c08a-11e6-9e74-92713e93bb6d.png)

**Comment by michaelst** [comment]
Refer to this page https://github.com/machour/yii2-notifications/blob/master/docs/Usage.md, I believe the change you are looking for is 
`<ul class="menu">
    <div id="notifications"></div>
</ul>`
