### ISSUE TITLE
Notification redirecting to the wrong action

### ISSUE THREAD

**Issue by GiovaniGil** [machour/yii2-notifications#29]
I my Notification class I have on return in the getRoute() method:
return ['customer/view', 'id' => $this->key_id];

But when I click in the notification I am redirected to:
index.php?r=notifications%2Fcustomer%2Fview&id=513
And, because of this, I'm gettig 404 error. How can I solve this problem?

**Comment by michaelst** [comment]
What should the url look like? maybe this would work `return ['/customer/view', 'id' => $this->key_id];` by adding the slash before customer

**Comment by machour** [comment]
Closing this as no feedback was given. @michaelst answer solves it.
