### ISSUE TITLE
Compatible php 5.4?

### ISSUE THREAD

**Issue by su-xiaolin** [machour/yii2-notifications#3]
Sorry about my english :(.

**Comment by machour** [comment]
Yii (Yes it is)
Not sure what this bug report is about.. :)

**Comment by su-xiaolin** [comment]
in machour\yii2\notifications\models\Notification line 72
$class = static::class;
::class syntax be added in php version 5.5.
http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class
you shold replace it with Component::className() method to compatible php 5.4.

**Comment by machour** [comment]
Thank you **a lot** for this bug report, I wasn't aware of ::class not being in 5.4.
Just fixed that call, and I'll fix my other packages :)
