### ISSUE TITLE
Mark all as read / delete all

### ISSUE THREAD

**Issue by pistej** [machour/yii2-notifications#33]
It is possible mark all displayed notifications as read or delete all notification at once?
One solution is: via javascript, similar function as markSeen

+ remove notifications if it's not present in server.pool response

Why is notification row only hidden and not removed permanently?

**Comment by drsdre** [comment]
You can delete all seen/flashed notifications by using the console command ./yii notifications/notifications/clean

Individual notification are deleted in the front-end using the action delete. This is carried out when you click x on a notification in the listSelector list.

If want to delete all notifications from the frontend, a new actionDeleteAll should be created probably together with a link in the listSelector interface. Feel free to send a PR for this.
