### ISSUE TITLE
Problem with date format

### ISSUE THREAD

**Issue by ilbassa** [machour/yii2-notifications#34]
Hi,
in the table the attribute "created at" is written as "dd/mm/yyyy" so the evaluation of the date is wrong because it suppose that the date is in the format "mm/dd/yyyy"...

we have changed NotificationController.php actionPoll():
```
public function actionPoll($seen = 0)
    {
        /** @var Notification $class */
        $class = $this->notificationClass;
        $models = $class::find()->where([
            'user_id' => $this->user_id,
            'seen' => $seen
        ])->all();
        $results = [];
        foreach ($models as $model) {
            /** @var Notification $model */
/*CHANGE*/
$date = \DateTime::createFromFormat('d/m/Y H:i:s', $model->created_at);
$date = $date->format('m-d-Y'); 
/*END CHANGE*/
            $results[] = [
                'id' => $model->id,
                'type' => $model->type,
                'title' => $model->getTitle(),
                'description' => $model->getDescription(),
                'url' => Url::to(['notifications/rnr', 'id' => $model->id]),
                'key' => $model->key,
                'date' =>$date
            ];
        }
        return $results;
    }
```
It is possible to fix the problem, formatting the date according to the Yii::$app->language or according to a parameter in the notification module section of the config file?

**Comment by machour** [comment]
Created_at is stored as a DateTime field. Should be Y-m-d H:i:s.
What database are you using ?

**Comment by ilbassa** [comment]
We are using ORACLE and the column datatype is DATE

**Comment by machour** [comment]
Would you be kind enough to test this for me ?

https://github.com/machour/yii2-notifications/tree/34-fix-date-formatting

I added a `dbDateFormat` parameter you can configure to suit your database format.

Here's the diff: https://github.com/machour/yii2-notifications/commit/1c99f89e82078b8c9e5a934a38637ce622e5e9ab

**Comment by ilbassa** [comment]
Hi, we have tested the branch and we confirm that now the evaluation of time passed is correct!
Thanks

**Comment by machour** [comment]
Merged into master. Have fun!
