### ISSUE TITLE
Project versioning

### ISSUE THREAD

**Issue by pistej** [machour/yii2-notifications#40]
I think, project has enough functionality to start versioning !?

**Comment by machour** [comment]
Sounds like a good thing to do 😄 
I'll look into that right after I merge your PR.

**Comment by machour** [comment]
Tagged the 1.0.0 version, thanks for the reminder !

**Comment by pistej** [comment]
Installation.md in docs folder needs to be updated too.

**Comment by machour** [comment]
Fixed !

**Comment by pistej** [comment]
I was thinking about:
php composer.phar require machour/yii2-notifications "^1.0.0"
or
php composer.phar require machour/yii2-notifications "~1.0"
otherwise there is not reason for versioning if developer use "*".

See: https://getcomposer.org/doc/articles/versions.md#tilde-version-range-
