### ISSUE TITLE
could it set don't route? 

### ISSUE THREAD

**Issue by chochoto** [machour/yii2-notifications#41]
Could it set the popup notification do not route but will set the seen = true when click the notification? thanks.

**Comment by machour** [comment]
Hi,

This is not supported by default, but you could implement it on your application like this I think:

- instead of URL, return '#' for this notification
- use jQuery to catch the click on that notification, prevent default and fire the ajax call yourself

Something like:

```javascript
$('#notifications [data-route="#"]').click(function () {
  $.get('<?= Url::to(['/notifications/notifications/read']) ?>', {
    id: $(this).data('id'),
  });
  return false;
});
```

**Comment by chochoto** [comment]
Thanks a lot.
