### ISSUE TITLE
message model and meet model

### ISSUE THREAD

**Issue by Crazylshao** [machour/yii2-notifications#44]
thank you provider yii2-notifications for us, i used it at mess,
i have a question: no message model and meet model
i don't know how to create it and do not konw the data_model structure.

**Comment by machour** [comment]
Hi @Crazylshao and thank you for the kind words :)
Message & Meeting were just example in the README.md

You can see in this repo how I set them up for the demonstration: https://github.com/machour/yii2-kitchen-sink/blob/master/models/Notification.php
