### ISSUE TITLE
Wrong model in Configuration.md

### ISSUE THREAD

**Issue by kakadanhem** [machour/yii2-notifications#45]
In the module config use below model:
`'notificationClass' => 'app\models\Notification',`

But in declaration, user below namespace:
`namespace backend\components;`

So it either change `namespace backend\components;` to `namespace app\models;` or change `'notificationClass' => 'app\models\Notification',` to `'notificationClass' => 'backend\components\Notification',`

**Comment by drsdre** [comment]
Hi kakadanhem. Thank you for suggestion. The example config and Notification.php class have been updated to be consistent using the single Yii2 application namespace.

Andre
