### ISSUE TITLE
Class 'machour\notifications\widgets\NotificationsWidget' not found

### ISSUE THREAD

**Issue by bhattaxay** [machour/yii2-notifications#51]
Hello,

I am going to integrate notification in backend admin, after installing widget successfully it throws me error as `Class 'machour\notifications\widgets\NotificationsWidget' not found`. Kindly help.
I have already include it as `use machour\notifications\widgets\NotificationsWidget`

**Comment by machour** [comment]
Hi,

The namespace is machour\\**yii2**\notifications\widgets
