### ISSUE TITLE
How to send notification to multiple users?

### ISSUE THREAD

**Issue by kwazaro** [machour/yii2-notifications#58]
Hello! How can I send notification for multiple users (for example, by role). I need a group of managers to see the notifications, but I can pass only one $admin_id in Notification::notify() function. Is there a way to notify all registered users, or other group of users?

**Comment by diegotejadav** [comment]
What if you try to group your users by role, and then you can find them as shown [here](https://stackoverflow.com/a/25440442)

**Comment by kwazaro** [comment]
Should I send notification to every user of specific role separately? Or I can do it for whole group of users at the same time?

**Comment by AlessandroCuba** [comment]
yo can do a foreach

ej.
`foreach($users as $user){
     Notification::notify(Notification::KEY_NEW_MESSAGE, $user->id, $message->id);
}`
