### ISSUE TITLE
Notifications are bad formatted?! Bug or my fault?

### ISSUE THREAD

**Issue by jkmssoft** [machour/yii2-notifications#63]
Hello,

my notifications look like the screenshot.
Is this a bug or do I have to define the css on my own way?

Regards
![notification](https://user-images.githubusercontent.com/19529106/70810746-9c390700-1dc4-11ea-8d2c-7fb870505006.png)

**Comment by machour** [comment]
Hi

You will have to handle your own CSS (it seems like there's a conflict with your template)
